// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Roma7-7-7/sso-notifier/internal/telegram (interfaces: EmergencyStore)
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/emergency.go . EmergencyStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dal "github.com/Roma7-7-7/sso-notifier/internal/dal"
	gomock "go.uber.org/mock/gomock"
)

// MockEmergencyStore is a mock of EmergencyStore interface.
type MockEmergencyStore struct {
	ctrl     *gomock.Controller
	recorder *MockEmergencyStoreMockRecorder
	isgomock struct{}
}

// MockEmergencyStoreMockRecorder is the mock recorder for MockEmergencyStore.
type MockEmergencyStoreMockRecorder struct {
	mock *MockEmergencyStore
}

// NewMockEmergencyStore creates a new mock instance.
func NewMockEmergencyStore(ctrl *gomock.Controller) *MockEmergencyStore {
	mock := &MockEmergencyStore{ctrl: ctrl}
	mock.recorder = &MockEmergencyStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmergencyStore) EXPECT() *MockEmergencyStoreMockRecorder {
	return m.recorder
}

// GetEmergencyState mocks base method.
func (m *MockEmergencyStore) GetEmergencyState() (dal.EmergencyState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmergencyState")
	ret0, _ := ret[0].(dal.EmergencyState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmergencyState indicates an expected call of GetEmergencyState.
func (mr *MockEmergencyStoreMockRecorder) GetEmergencyState() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmergencyState", reflect.TypeOf((*MockEmergencyStore)(nil).GetEmergencyState))
}
