// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Roma7-7-7/sso-notifier/internal/telegram (interfaces: Notifications)
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/notifications.go . Notifications
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockNotifications is a mock of Notifications interface.
type MockNotifications struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationsMockRecorder
	isgomock struct{}
}

// MockNotificationsMockRecorder is the mock recorder for MockNotifications.
type MockNotificationsMockRecorder struct {
	mock *MockNotifications
}

// NewMockNotifications creates a new mock instance.
func NewMockNotifications(ctrl *gomock.Controller) *MockNotifications {
	mock := &MockNotifications{ctrl: ctrl}
	mock.recorder = &MockNotificationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotifications) EXPECT() *MockNotificationsMockRecorder {
	return m.recorder
}

// NotifyPowerSupplySchedule mocks base method.
func (m *MockNotifications) NotifyPowerSupplySchedule(ctx context.Context, chatID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyPowerSupplySchedule", ctx, chatID)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyPowerSupplySchedule indicates an expected call of NotifyPowerSupplySchedule.
func (mr *MockNotificationsMockRecorder) NotifyPowerSupplySchedule(ctx, chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyPowerSupplySchedule", reflect.TypeOf((*MockNotifications)(nil).NotifyPowerSupplySchedule), ctx, chatID)
}
