// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Roma7-7-7/sso-notifier/internal/telegram (interfaces: Subscriptions)
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/subscriptions.go . Subscriptions
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dal "github.com/Roma7-7-7/sso-notifier/internal/dal"
	gomock "go.uber.org/mock/gomock"
)

// MockSubscriptions is a mock of Subscriptions interface.
type MockSubscriptions struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionsMockRecorder
	isgomock struct{}
}

// MockSubscriptionsMockRecorder is the mock recorder for MockSubscriptions.
type MockSubscriptionsMockRecorder struct {
	mock *MockSubscriptions
}

// NewMockSubscriptions creates a new mock instance.
func NewMockSubscriptions(ctrl *gomock.Controller) *MockSubscriptions {
	mock := &MockSubscriptions{ctrl: ctrl}
	mock.recorder = &MockSubscriptionsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptions) EXPECT() *MockSubscriptionsMockRecorder {
	return m.recorder
}

// GetSettings mocks base method.
func (m *MockSubscriptions) GetSettings(chatID int64) (map[dal.SettingKey]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSettings", chatID)
	ret0, _ := ret[0].(map[dal.SettingKey]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSettings indicates an expected call of GetSettings.
func (mr *MockSubscriptionsMockRecorder) GetSettings(chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSettings", reflect.TypeOf((*MockSubscriptions)(nil).GetSettings), chatID)
}

// GetSubscribedGroups mocks base method.
func (m *MockSubscriptions) GetSubscribedGroups(chatID int64) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscribedGroups", chatID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscribedGroups indicates an expected call of GetSubscribedGroups.
func (mr *MockSubscriptionsMockRecorder) GetSubscribedGroups(chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscribedGroups", reflect.TypeOf((*MockSubscriptions)(nil).GetSubscribedGroups), chatID)
}

// IsSubscribed mocks base method.
func (m *MockSubscriptions) IsSubscribed(chatID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSubscribed", chatID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsSubscribed indicates an expected call of IsSubscribed.
func (mr *MockSubscriptionsMockRecorder) IsSubscribed(chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSubscribed", reflect.TypeOf((*MockSubscriptions)(nil).IsSubscribed), chatID)
}

// ToggleGroupSubscription mocks base method.
func (m *MockSubscriptions) ToggleGroupSubscription(chatID int64, number string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToggleGroupSubscription", chatID, number)
	ret0, _ := ret[0].(error)
	return ret0
}

// ToggleGroupSubscription indicates an expected call of ToggleGroupSubscription.
func (mr *MockSubscriptionsMockRecorder) ToggleGroupSubscription(chatID, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToggleGroupSubscription", reflect.TypeOf((*MockSubscriptions)(nil).ToggleGroupSubscription), chatID, number)
}

// ToggleSetting mocks base method.
func (m *MockSubscriptions) ToggleSetting(chatID int64, key dal.SettingKey, defaultValue bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToggleSetting", chatID, key, defaultValue)
	ret0, _ := ret[0].(error)
	return ret0
}

// ToggleSetting indicates an expected call of ToggleSetting.
func (mr *MockSubscriptionsMockRecorder) ToggleSetting(chatID, key, defaultValue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToggleSetting", reflect.TypeOf((*MockSubscriptions)(nil).ToggleSetting), chatID, key, defaultValue)
}

// Unsubscribe mocks base method.
func (m *MockSubscriptions) Unsubscribe(chatID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unsubscribe", chatID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unsubscribe indicates an expected call of Unsubscribe.
func (mr *MockSubscriptionsMockRecorder) Unsubscribe(chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unsubscribe", reflect.TypeOf((*MockSubscriptions)(nil).Unsubscribe), chatID)
}
