// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Roma7-7-7/sso-notifier/internal/service (interfaces: AlertsStore)
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/alerts.go . AlertsStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	dal "github.com/Roma7-7-7/sso-notifier/internal/dal"
	gomock "go.uber.org/mock/gomock"
)

// MockAlertsStore is a mock of AlertsStore interface.
type MockAlertsStore struct {
	ctrl     *gomock.Controller
	recorder *MockAlertsStoreMockRecorder
	isgomock struct{}
}

// MockAlertsStoreMockRecorder is the mock recorder for MockAlertsStore.
type MockAlertsStoreMockRecorder struct {
	mock *MockAlertsStore
}

// NewMockAlertsStore creates a new mock instance.
func NewMockAlertsStore(ctrl *gomock.Controller) *MockAlertsStore {
	mock := &MockAlertsStore{ctrl: ctrl}
	mock.recorder = &MockAlertsStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAlertsStore) EXPECT() *MockAlertsStoreMockRecorder {
	return m.recorder
}

// GetAlert mocks base method.
func (m *MockAlertsStore) GetAlert(key dal.AlertKey) (time.Time, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAlert", key)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAlert indicates an expected call of GetAlert.
func (mr *MockAlertsStoreMockRecorder) GetAlert(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAlert", reflect.TypeOf((*MockAlertsStore)(nil).GetAlert), key)
}

// PutAlert mocks base method.
func (m *MockAlertsStore) PutAlert(key dal.AlertKey, sentAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutAlert", key, sentAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutAlert indicates an expected call of PutAlert.
func (mr *MockAlertsStoreMockRecorder) PutAlert(key, sentAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutAlert", reflect.TypeOf((*MockAlertsStore)(nil).PutAlert), key, sentAt)
}
