// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Roma7-7-7/sso-notifier/internal/service (interfaces: AlertsStore,AlertsEmergencyStore)
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/alerts.go . AlertsStore,AlertsEmergencyStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	dal "github.com/Roma7-7-7/sso-notifier/internal/dal"
	gomock "go.uber.org/mock/gomock"
)

// MockAlertsStore is a mock of AlertsStore interface.
type MockAlertsStore struct {
	ctrl     *gomock.Controller
	recorder *MockAlertsStoreMockRecorder
	isgomock struct{}
}

// MockAlertsStoreMockRecorder is the mock recorder for MockAlertsStore.
type MockAlertsStoreMockRecorder struct {
	mock *MockAlertsStore
}

// NewMockAlertsStore creates a new mock instance.
func NewMockAlertsStore(ctrl *gomock.Controller) *MockAlertsStore {
	mock := &MockAlertsStore{ctrl: ctrl}
	mock.recorder = &MockAlertsStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAlertsStore) EXPECT() *MockAlertsStoreMockRecorder {
	return m.recorder
}

// CleanupAlerts mocks base method.
func (m *MockAlertsStore) CleanupAlerts(olderThan time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupAlerts", olderThan)
	ret0, _ := ret[0].(error)
	return ret0
}

// CleanupAlerts indicates an expected call of CleanupAlerts.
func (mr *MockAlertsStoreMockRecorder) CleanupAlerts(olderThan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupAlerts", reflect.TypeOf((*MockAlertsStore)(nil).CleanupAlerts), olderThan)
}

// GetAlert mocks base method.
func (m *MockAlertsStore) GetAlert(key dal.AlertKey) (time.Time, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAlert", key)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAlert indicates an expected call of GetAlert.
func (mr *MockAlertsStoreMockRecorder) GetAlert(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAlert", reflect.TypeOf((*MockAlertsStore)(nil).GetAlert), key)
}

// PutAlert mocks base method.
func (m *MockAlertsStore) PutAlert(key dal.AlertKey, sentAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutAlert", key, sentAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutAlert indicates an expected call of PutAlert.
func (mr *MockAlertsStoreMockRecorder) PutAlert(key, sentAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutAlert", reflect.TypeOf((*MockAlertsStore)(nil).PutAlert), key, sentAt)
}

// MockAlertsEmergencyStore is a mock of AlertsEmergencyStore interface.
type MockAlertsEmergencyStore struct {
	ctrl     *gomock.Controller
	recorder *MockAlertsEmergencyStoreMockRecorder
	isgomock struct{}
}

// MockAlertsEmergencyStoreMockRecorder is the mock recorder for MockAlertsEmergencyStore.
type MockAlertsEmergencyStoreMockRecorder struct {
	mock *MockAlertsEmergencyStore
}

// NewMockAlertsEmergencyStore creates a new mock instance.
func NewMockAlertsEmergencyStore(ctrl *gomock.Controller) *MockAlertsEmergencyStore {
	mock := &MockAlertsEmergencyStore{ctrl: ctrl}
	mock.recorder = &MockAlertsEmergencyStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAlertsEmergencyStore) EXPECT() *MockAlertsEmergencyStoreMockRecorder {
	return m.recorder
}

// GetEmergencyState mocks base method.
func (m *MockAlertsEmergencyStore) GetEmergencyState() (dal.EmergencyState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmergencyState")
	ret0, _ := ret[0].(dal.EmergencyState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmergencyState indicates an expected call of GetEmergencyState.
func (mr *MockAlertsEmergencyStoreMockRecorder) GetEmergencyState() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmergencyState", reflect.TypeOf((*MockAlertsEmergencyStore)(nil).GetEmergencyState))
}
