// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Roma7-7-7/sso-notifier/internal/service (interfaces: Calendar)
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/calendar.go . Calendar
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	calendar "github.com/Roma7-7-7/sso-notifier/internal/calendar"
	gomock "go.uber.org/mock/gomock"
)

// MockCalendar is a mock of Calendar interface.
type MockCalendar struct {
	ctrl     *gomock.Controller
	recorder *MockCalendarMockRecorder
	isgomock struct{}
}

// MockCalendarMockRecorder is the mock recorder for MockCalendar.
type MockCalendarMockRecorder struct {
	mock *MockCalendar
}

// NewMockCalendar creates a new mock instance.
func NewMockCalendar(ctrl *gomock.Controller) *MockCalendar {
	mock := &MockCalendar{ctrl: ctrl}
	mock.recorder = &MockCalendarMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCalendar) EXPECT() *MockCalendarMockRecorder {
	return m.recorder
}

// DeleteEvent mocks base method.
func (m *MockCalendar) DeleteEvent(ctx context.Context, calendarID, eventID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEvent", ctx, calendarID, eventID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEvent indicates an expected call of DeleteEvent.
func (mr *MockCalendarMockRecorder) DeleteEvent(ctx, calendarID, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEvent", reflect.TypeOf((*MockCalendar)(nil).DeleteEvent), ctx, calendarID, eventID)
}

// InsertEvent mocks base method.
func (m *MockCalendar) InsertEvent(ctx context.Context, calendarID, summary string, start, end time.Time, params calendar.EventParams) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertEvent", ctx, calendarID, summary, start, end, params)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertEvent indicates an expected call of InsertEvent.
func (mr *MockCalendarMockRecorder) InsertEvent(ctx, calendarID, summary, start, end, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertEvent", reflect.TypeOf((*MockCalendar)(nil).InsertEvent), ctx, calendarID, summary, start, end, params)
}

// ListOurEvents mocks base method.
func (m *MockCalendar) ListOurEvents(ctx context.Context, calendarID string, timeMin, timeMax time.Time) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOurEvents", ctx, calendarID, timeMin, timeMax)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOurEvents indicates an expected call of ListOurEvents.
func (mr *MockCalendarMockRecorder) ListOurEvents(ctx, calendarID, timeMin, timeMax any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOurEvents", reflect.TypeOf((*MockCalendar)(nil).ListOurEvents), ctx, calendarID, timeMin, timeMax)
}
