// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Roma7-7-7/sso-notifier/internal/service (interfaces: NotificationsStore)
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/notifications.go . NotificationsStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	dal "github.com/Roma7-7-7/sso-notifier/internal/dal"
	gomock "go.uber.org/mock/gomock"
)

// MockNotificationsStore is a mock of NotificationsStore interface.
type MockNotificationsStore struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationsStoreMockRecorder
	isgomock struct{}
}

// MockNotificationsStoreMockRecorder is the mock recorder for MockNotificationsStore.
type MockNotificationsStoreMockRecorder struct {
	mock *MockNotificationsStore
}

// NewMockNotificationsStore creates a new mock instance.
func NewMockNotificationsStore(ctrl *gomock.Controller) *MockNotificationsStore {
	mock := &MockNotificationsStore{ctrl: ctrl}
	mock.recorder = &MockNotificationsStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationsStore) EXPECT() *MockNotificationsStoreMockRecorder {
	return m.recorder
}

// CleanupNotificationStates mocks base method.
func (m *MockNotificationsStore) CleanupNotificationStates(olderThan time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupNotificationStates", olderThan)
	ret0, _ := ret[0].(error)
	return ret0
}

// CleanupNotificationStates indicates an expected call of CleanupNotificationStates.
func (mr *MockNotificationsStoreMockRecorder) CleanupNotificationStates(olderThan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupNotificationStates", reflect.TypeOf((*MockNotificationsStore)(nil).CleanupNotificationStates), olderThan)
}

// GetNotificationState mocks base method.
func (m *MockNotificationsStore) GetNotificationState(chatID int64, date dal.Date) (dal.NotificationState, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotificationState", chatID, date)
	ret0, _ := ret[0].(dal.NotificationState)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetNotificationState indicates an expected call of GetNotificationState.
func (mr *MockNotificationsStoreMockRecorder) GetNotificationState(chatID, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotificationState", reflect.TypeOf((*MockNotificationsStore)(nil).GetNotificationState), chatID, date)
}

// PutNotificationState mocks base method.
func (m *MockNotificationsStore) PutNotificationState(state dal.NotificationState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutNotificationState", state)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutNotificationState indicates an expected call of PutNotificationState.
func (mr *MockNotificationsStoreMockRecorder) PutNotificationState(state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutNotificationState", reflect.TypeOf((*MockNotificationsStore)(nil).PutNotificationState), state)
}
