// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Roma7-7-7/sso-notifier/internal/service (interfaces: NotificationsStore,NotificationsEmergencyStore)
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/notifications.go . NotificationsStore,NotificationsEmergencyStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	dal "github.com/Roma7-7-7/sso-notifier/internal/dal"
	gomock "go.uber.org/mock/gomock"
)

// MockNotificationsStore is a mock of NotificationsStore interface.
type MockNotificationsStore struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationsStoreMockRecorder
	isgomock struct{}
}

// MockNotificationsStoreMockRecorder is the mock recorder for MockNotificationsStore.
type MockNotificationsStoreMockRecorder struct {
	mock *MockNotificationsStore
}

// NewMockNotificationsStore creates a new mock instance.
func NewMockNotificationsStore(ctrl *gomock.Controller) *MockNotificationsStore {
	mock := &MockNotificationsStore{ctrl: ctrl}
	mock.recorder = &MockNotificationsStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationsStore) EXPECT() *MockNotificationsStoreMockRecorder {
	return m.recorder
}

// CleanupNotificationStates mocks base method.
func (m *MockNotificationsStore) CleanupNotificationStates(olderThan time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupNotificationStates", olderThan)
	ret0, _ := ret[0].(error)
	return ret0
}

// CleanupNotificationStates indicates an expected call of CleanupNotificationStates.
func (mr *MockNotificationsStoreMockRecorder) CleanupNotificationStates(olderThan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupNotificationStates", reflect.TypeOf((*MockNotificationsStore)(nil).CleanupNotificationStates), olderThan)
}

// GetNotificationState mocks base method.
func (m *MockNotificationsStore) GetNotificationState(chatID int64, date dal.Date) (dal.NotificationState, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotificationState", chatID, date)
	ret0, _ := ret[0].(dal.NotificationState)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetNotificationState indicates an expected call of GetNotificationState.
func (mr *MockNotificationsStoreMockRecorder) GetNotificationState(chatID, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotificationState", reflect.TypeOf((*MockNotificationsStore)(nil).GetNotificationState), chatID, date)
}

// PutNotificationState mocks base method.
func (m *MockNotificationsStore) PutNotificationState(state dal.NotificationState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutNotificationState", state)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutNotificationState indicates an expected call of PutNotificationState.
func (mr *MockNotificationsStoreMockRecorder) PutNotificationState(state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutNotificationState", reflect.TypeOf((*MockNotificationsStore)(nil).PutNotificationState), state)
}

// MockNotificationsEmergencyStore is a mock of NotificationsEmergencyStore interface.
type MockNotificationsEmergencyStore struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationsEmergencyStoreMockRecorder
	isgomock struct{}
}

// MockNotificationsEmergencyStoreMockRecorder is the mock recorder for MockNotificationsEmergencyStore.
type MockNotificationsEmergencyStoreMockRecorder struct {
	mock *MockNotificationsEmergencyStore
}

// NewMockNotificationsEmergencyStore creates a new mock instance.
func NewMockNotificationsEmergencyStore(ctrl *gomock.Controller) *MockNotificationsEmergencyStore {
	mock := &MockNotificationsEmergencyStore{ctrl: ctrl}
	mock.recorder = &MockNotificationsEmergencyStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationsEmergencyStore) EXPECT() *MockNotificationsEmergencyStoreMockRecorder {
	return m.recorder
}

// GetEmergencyNotification mocks base method.
func (m *MockNotificationsEmergencyStore) GetEmergencyNotification(chatID int64) (time.Time, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmergencyNotification", chatID)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetEmergencyNotification indicates an expected call of GetEmergencyNotification.
func (mr *MockNotificationsEmergencyStoreMockRecorder) GetEmergencyNotification(chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmergencyNotification", reflect.TypeOf((*MockNotificationsEmergencyStore)(nil).GetEmergencyNotification), chatID)
}

// GetEmergencyState mocks base method.
func (m *MockNotificationsEmergencyStore) GetEmergencyState() (dal.EmergencyState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmergencyState")
	ret0, _ := ret[0].(dal.EmergencyState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmergencyState indicates an expected call of GetEmergencyState.
func (mr *MockNotificationsEmergencyStoreMockRecorder) GetEmergencyState() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmergencyState", reflect.TypeOf((*MockNotificationsEmergencyStore)(nil).GetEmergencyState))
}

// SetEmergencyNotification mocks base method.
func (m *MockNotificationsEmergencyStore) SetEmergencyNotification(chatID int64, sentAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetEmergencyNotification", chatID, sentAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetEmergencyNotification indicates an expected call of SetEmergencyNotification.
func (mr *MockNotificationsEmergencyStoreMockRecorder) SetEmergencyNotification(chatID, sentAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEmergencyNotification", reflect.TypeOf((*MockNotificationsEmergencyStore)(nil).SetEmergencyNotification), chatID, sentAt)
}
