// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Roma7-7-7/sso-notifier/internal/service (interfaces: ShutdownsStore,ShutdownsProvider)
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/shutdowns.go . ShutdownsStore,ShutdownsProvider
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dal "github.com/Roma7-7-7/sso-notifier/internal/dal"
	gomock "go.uber.org/mock/gomock"
)

// MockShutdownsStore is a mock of ShutdownsStore interface.
type MockShutdownsStore struct {
	ctrl     *gomock.Controller
	recorder *MockShutdownsStoreMockRecorder
	isgomock struct{}
}

// MockShutdownsStoreMockRecorder is the mock recorder for MockShutdownsStore.
type MockShutdownsStoreMockRecorder struct {
	mock *MockShutdownsStore
}

// NewMockShutdownsStore creates a new mock instance.
func NewMockShutdownsStore(ctrl *gomock.Controller) *MockShutdownsStore {
	mock := &MockShutdownsStore{ctrl: ctrl}
	mock.recorder = &MockShutdownsStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShutdownsStore) EXPECT() *MockShutdownsStoreMockRecorder {
	return m.recorder
}

// GetEmergencyState mocks base method.
func (m *MockShutdownsStore) GetEmergencyState() (dal.EmergencyState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmergencyState")
	ret0, _ := ret[0].(dal.EmergencyState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmergencyState indicates an expected call of GetEmergencyState.
func (mr *MockShutdownsStoreMockRecorder) GetEmergencyState() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmergencyState", reflect.TypeOf((*MockShutdownsStore)(nil).GetEmergencyState))
}

// GetShutdowns mocks base method.
func (m *MockShutdownsStore) GetShutdowns(d dal.Date) (dal.Shutdowns, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShutdowns", d)
	ret0, _ := ret[0].(dal.Shutdowns)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetShutdowns indicates an expected call of GetShutdowns.
func (mr *MockShutdownsStoreMockRecorder) GetShutdowns(d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShutdowns", reflect.TypeOf((*MockShutdownsStore)(nil).GetShutdowns), d)
}

// PutShutdowns mocks base method.
func (m *MockShutdownsStore) PutShutdowns(d dal.Date, s dal.Shutdowns) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutShutdowns", d, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutShutdowns indicates an expected call of PutShutdowns.
func (mr *MockShutdownsStoreMockRecorder) PutShutdowns(d, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutShutdowns", reflect.TypeOf((*MockShutdownsStore)(nil).PutShutdowns), d, s)
}

// SetEmergencyState mocks base method.
func (m *MockShutdownsStore) SetEmergencyState(state dal.EmergencyState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetEmergencyState", state)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetEmergencyState indicates an expected call of SetEmergencyState.
func (mr *MockShutdownsStoreMockRecorder) SetEmergencyState(state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEmergencyState", reflect.TypeOf((*MockShutdownsStore)(nil).SetEmergencyState), state)
}

// MockShutdownsProvider is a mock of ShutdownsProvider interface.
type MockShutdownsProvider struct {
	ctrl     *gomock.Controller
	recorder *MockShutdownsProviderMockRecorder
	isgomock struct{}
}

// MockShutdownsProviderMockRecorder is the mock recorder for MockShutdownsProvider.
type MockShutdownsProviderMockRecorder struct {
	mock *MockShutdownsProvider
}

// NewMockShutdownsProvider creates a new mock instance.
func NewMockShutdownsProvider(ctrl *gomock.Controller) *MockShutdownsProvider {
	mock := &MockShutdownsProvider{ctrl: ctrl}
	mock.recorder = &MockShutdownsProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShutdownsProvider) EXPECT() *MockShutdownsProviderMockRecorder {
	return m.recorder
}

// Shutdowns mocks base method.
func (m *MockShutdownsProvider) Shutdowns(ctx context.Context) (dal.Shutdowns, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shutdowns", ctx)
	ret0, _ := ret[0].(dal.Shutdowns)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Shutdowns indicates an expected call of Shutdowns.
func (mr *MockShutdownsProviderMockRecorder) Shutdowns(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdowns", reflect.TypeOf((*MockShutdownsProvider)(nil).Shutdowns), ctx)
}

// ShutdownsNext mocks base method.
func (m *MockShutdownsProvider) ShutdownsNext(ctx context.Context) (dal.Shutdowns, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShutdownsNext", ctx)
	ret0, _ := ret[0].(dal.Shutdowns)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShutdownsNext indicates an expected call of ShutdownsNext.
func (mr *MockShutdownsProviderMockRecorder) ShutdownsNext(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShutdownsNext", reflect.TypeOf((*MockShutdownsProvider)(nil).ShutdownsNext), ctx)
}
