// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Roma7-7-7/sso-notifier/internal/service (interfaces: SubscriptionsStore)
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/subscriptions.go . SubscriptionsStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dal "github.com/Roma7-7-7/sso-notifier/internal/dal"
	gomock "go.uber.org/mock/gomock"
)

// MockSubscriptionsStore is a mock of SubscriptionsStore interface.
type MockSubscriptionsStore struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionsStoreMockRecorder
	isgomock struct{}
}

// MockSubscriptionsStoreMockRecorder is the mock recorder for MockSubscriptionsStore.
type MockSubscriptionsStoreMockRecorder struct {
	mock *MockSubscriptionsStore
}

// NewMockSubscriptionsStore creates a new mock instance.
func NewMockSubscriptionsStore(ctrl *gomock.Controller) *MockSubscriptionsStore {
	mock := &MockSubscriptionsStore{ctrl: ctrl}
	mock.recorder = &MockSubscriptionsStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionsStore) EXPECT() *MockSubscriptionsStoreMockRecorder {
	return m.recorder
}

// ExistsSubscription mocks base method.
func (m *MockSubscriptionsStore) ExistsSubscription(chatID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsSubscription", chatID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsSubscription indicates an expected call of ExistsSubscription.
func (mr *MockSubscriptionsStoreMockRecorder) ExistsSubscription(chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsSubscription", reflect.TypeOf((*MockSubscriptionsStore)(nil).ExistsSubscription), chatID)
}

// GetAllSubscriptions mocks base method.
func (m *MockSubscriptionsStore) GetAllSubscriptions() ([]dal.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllSubscriptions")
	ret0, _ := ret[0].([]dal.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllSubscriptions indicates an expected call of GetAllSubscriptions.
func (mr *MockSubscriptionsStoreMockRecorder) GetAllSubscriptions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllSubscriptions", reflect.TypeOf((*MockSubscriptionsStore)(nil).GetAllSubscriptions))
}

// GetSubscription mocks base method.
func (m *MockSubscriptionsStore) GetSubscription(chatID int64) (dal.Subscription, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscription", chatID)
	ret0, _ := ret[0].(dal.Subscription)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetSubscription indicates an expected call of GetSubscription.
func (mr *MockSubscriptionsStoreMockRecorder) GetSubscription(chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscription", reflect.TypeOf((*MockSubscriptionsStore)(nil).GetSubscription), chatID)
}

// Purge mocks base method.
func (m *MockSubscriptionsStore) Purge(chatID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Purge", chatID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Purge indicates an expected call of Purge.
func (mr *MockSubscriptionsStoreMockRecorder) Purge(chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Purge", reflect.TypeOf((*MockSubscriptionsStore)(nil).Purge), chatID)
}

// PutSubscription mocks base method.
func (m *MockSubscriptionsStore) PutSubscription(sub dal.Subscription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutSubscription", sub)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutSubscription indicates an expected call of PutSubscription.
func (mr *MockSubscriptionsStoreMockRecorder) PutSubscription(sub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutSubscription", reflect.TypeOf((*MockSubscriptionsStore)(nil).PutSubscription), sub)
}
